synonyms_select.settings:
  type: config_entity
  label: 'Widget configuration'
  mapping:
    default_wording:
      type: string
      label: 'Default wording for this widget'

synonyms_select.behavior.*:
  type: config_entity
  label: 'Behavior configuration'
  mapping:
    status:
      type: boolean
      label: 'Status'
    wording:
      type: string
      label: 'Behavior service wording'
